// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aegisthus.proto

package com.netflix.aegisthus.message;

public final class AegisthusProtos {
  private AegisthusProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ColumnOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes rowKey = 1;
    /**
     * <code>required bytes rowKey = 1;</code>
     */
    boolean hasRowKey();
    /**
     * <code>required bytes rowKey = 1;</code>
     */
    com.google.protobuf.ByteString getRowKey();

    // required int64 deletedAt = 2;
    /**
     * <code>required int64 deletedAt = 2;</code>
     */
    boolean hasDeletedAt();
    /**
     * <code>required int64 deletedAt = 2;</code>
     */
    long getDeletedAt();

    // optional .aegisthus.Column.ColumnType columnType = 3 [default = NORMAL];
    /**
     * <code>optional .aegisthus.Column.ColumnType columnType = 3 [default = NORMAL];</code>
     */
    boolean hasColumnType();
    /**
     * <code>optional .aegisthus.Column.ColumnType columnType = 3 [default = NORMAL];</code>
     */
    com.netflix.aegisthus.message.AegisthusProtos.Column.ColumnType getColumnType();

    // required bytes columnName = 4;
    /**
     * <code>required bytes columnName = 4;</code>
     */
    boolean hasColumnName();
    /**
     * <code>required bytes columnName = 4;</code>
     */
    com.google.protobuf.ByteString getColumnName();

    // optional bytes value = 5;
    /**
     * <code>optional bytes value = 5;</code>
     */
    boolean hasValue();
    /**
     * <code>optional bytes value = 5;</code>
     */
    com.google.protobuf.ByteString getValue();

    // optional int64 timestamp = 6;
    /**
     * <code>optional int64 timestamp = 6;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 6;</code>
     */
    long getTimestamp();

    // optional int64 ttl = 7;
    /**
     * <code>optional int64 ttl = 7;</code>
     */
    boolean hasTtl();
    /**
     * <code>optional int64 ttl = 7;</code>
     */
    long getTtl();
  }
  /**
   * Protobuf type {@code aegisthus.Column}
   */
  public static final class Column extends
      com.google.protobuf.GeneratedMessage
      implements ColumnOrBuilder {
    // Use Column.newBuilder() to construct.
    private Column(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Column(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Column defaultInstance;
    public static Column getDefaultInstance() {
      return defaultInstance;
    }

    public Column getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Column(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              rowKey_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              deletedAt_ = input.readInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.netflix.aegisthus.message.AegisthusProtos.Column.ColumnType value = com.netflix.aegisthus.message.AegisthusProtos.Column.ColumnType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                columnType_ = value;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              columnName_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              value_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              timestamp_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              ttl_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netflix.aegisthus.message.AegisthusProtos.internal_static_aegisthus_Column_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netflix.aegisthus.message.AegisthusProtos.internal_static_aegisthus_Column_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netflix.aegisthus.message.AegisthusProtos.Column.class, com.netflix.aegisthus.message.AegisthusProtos.Column.Builder.class);
    }

    public static com.google.protobuf.Parser<Column> PARSER =
        new com.google.protobuf.AbstractParser<Column>() {
      public Column parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Column(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Column> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code aegisthus.Column.ColumnType}
     */
    public enum ColumnType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NORMAL = 0;</code>
       */
      NORMAL(0, 0),
      /**
       * <code>DELETED = 1;</code>
       */
      DELETED(1, 1),
      /**
       * <code>EXPIRING = 2;</code>
       */
      EXPIRING(2, 2),
      /**
       * <code>COUNTER = 3;</code>
       */
      COUNTER(3, 3),
      ;

      /**
       * <code>NORMAL = 0;</code>
       */
      public static final int NORMAL_VALUE = 0;
      /**
       * <code>DELETED = 1;</code>
       */
      public static final int DELETED_VALUE = 1;
      /**
       * <code>EXPIRING = 2;</code>
       */
      public static final int EXPIRING_VALUE = 2;
      /**
       * <code>COUNTER = 3;</code>
       */
      public static final int COUNTER_VALUE = 3;


      public final int getNumber() { return value; }

      public static ColumnType valueOf(int value) {
        switch (value) {
          case 0: return NORMAL;
          case 1: return DELETED;
          case 2: return EXPIRING;
          case 3: return COUNTER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ColumnType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ColumnType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ColumnType>() {
              public ColumnType findValueByNumber(int number) {
                return ColumnType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.netflix.aegisthus.message.AegisthusProtos.Column.getDescriptor().getEnumTypes().get(0);
      }

      private static final ColumnType[] VALUES = values();

      public static ColumnType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ColumnType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:aegisthus.Column.ColumnType)
    }

    private int bitField0_;
    // required bytes rowKey = 1;
    public static final int ROWKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString rowKey_;
    /**
     * <code>required bytes rowKey = 1;</code>
     */
    public boolean hasRowKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes rowKey = 1;</code>
     */
    public com.google.protobuf.ByteString getRowKey() {
      return rowKey_;
    }

    // required int64 deletedAt = 2;
    public static final int DELETEDAT_FIELD_NUMBER = 2;
    private long deletedAt_;
    /**
     * <code>required int64 deletedAt = 2;</code>
     */
    public boolean hasDeletedAt() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 deletedAt = 2;</code>
     */
    public long getDeletedAt() {
      return deletedAt_;
    }

    // optional .aegisthus.Column.ColumnType columnType = 3 [default = NORMAL];
    public static final int COLUMNTYPE_FIELD_NUMBER = 3;
    private com.netflix.aegisthus.message.AegisthusProtos.Column.ColumnType columnType_;
    /**
     * <code>optional .aegisthus.Column.ColumnType columnType = 3 [default = NORMAL];</code>
     */
    public boolean hasColumnType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .aegisthus.Column.ColumnType columnType = 3 [default = NORMAL];</code>
     */
    public com.netflix.aegisthus.message.AegisthusProtos.Column.ColumnType getColumnType() {
      return columnType_;
    }

    // required bytes columnName = 4;
    public static final int COLUMNNAME_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString columnName_;
    /**
     * <code>required bytes columnName = 4;</code>
     */
    public boolean hasColumnName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes columnName = 4;</code>
     */
    public com.google.protobuf.ByteString getColumnName() {
      return columnName_;
    }

    // optional bytes value = 5;
    public static final int VALUE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>optional bytes value = 5;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes value = 5;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    // optional int64 timestamp = 6;
    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 6;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 timestamp = 6;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // optional int64 ttl = 7;
    public static final int TTL_FIELD_NUMBER = 7;
    private long ttl_;
    /**
     * <code>optional int64 ttl = 7;</code>
     */
    public boolean hasTtl() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 ttl = 7;</code>
     */
    public long getTtl() {
      return ttl_;
    }

    private void initFields() {
      rowKey_ = com.google.protobuf.ByteString.EMPTY;
      deletedAt_ = 0L;
      columnType_ = com.netflix.aegisthus.message.AegisthusProtos.Column.ColumnType.NORMAL;
      columnName_ = com.google.protobuf.ByteString.EMPTY;
      value_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = 0L;
      ttl_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRowKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeletedAt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasColumnName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, rowKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, deletedAt_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, columnType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, columnName_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, value_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, timestamp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, ttl_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, rowKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, deletedAt_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, columnType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, columnName_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, value_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, timestamp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, ttl_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.netflix.aegisthus.message.AegisthusProtos.Column parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.aegisthus.message.AegisthusProtos.Column parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.aegisthus.message.AegisthusProtos.Column parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.aegisthus.message.AegisthusProtos.Column parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.aegisthus.message.AegisthusProtos.Column parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.netflix.aegisthus.message.AegisthusProtos.Column parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.netflix.aegisthus.message.AegisthusProtos.Column parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.netflix.aegisthus.message.AegisthusProtos.Column parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.netflix.aegisthus.message.AegisthusProtos.Column parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.netflix.aegisthus.message.AegisthusProtos.Column parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.netflix.aegisthus.message.AegisthusProtos.Column prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code aegisthus.Column}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.netflix.aegisthus.message.AegisthusProtos.ColumnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netflix.aegisthus.message.AegisthusProtos.internal_static_aegisthus_Column_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netflix.aegisthus.message.AegisthusProtos.internal_static_aegisthus_Column_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netflix.aegisthus.message.AegisthusProtos.Column.class, com.netflix.aegisthus.message.AegisthusProtos.Column.Builder.class);
      }

      // Construct using com.netflix.aegisthus.message.AegisthusProtos.Column.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rowKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        deletedAt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        columnType_ = com.netflix.aegisthus.message.AegisthusProtos.Column.ColumnType.NORMAL;
        bitField0_ = (bitField0_ & ~0x00000004);
        columnName_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        ttl_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netflix.aegisthus.message.AegisthusProtos.internal_static_aegisthus_Column_descriptor;
      }

      public com.netflix.aegisthus.message.AegisthusProtos.Column getDefaultInstanceForType() {
        return com.netflix.aegisthus.message.AegisthusProtos.Column.getDefaultInstance();
      }

      public com.netflix.aegisthus.message.AegisthusProtos.Column build() {
        com.netflix.aegisthus.message.AegisthusProtos.Column result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netflix.aegisthus.message.AegisthusProtos.Column buildPartial() {
        com.netflix.aegisthus.message.AegisthusProtos.Column result = new com.netflix.aegisthus.message.AegisthusProtos.Column(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rowKey_ = rowKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deletedAt_ = deletedAt_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.columnType_ = columnType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.columnName_ = columnName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.ttl_ = ttl_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netflix.aegisthus.message.AegisthusProtos.Column) {
          return mergeFrom((com.netflix.aegisthus.message.AegisthusProtos.Column)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netflix.aegisthus.message.AegisthusProtos.Column other) {
        if (other == com.netflix.aegisthus.message.AegisthusProtos.Column.getDefaultInstance()) return this;
        if (other.hasRowKey()) {
          setRowKey(other.getRowKey());
        }
        if (other.hasDeletedAt()) {
          setDeletedAt(other.getDeletedAt());
        }
        if (other.hasColumnType()) {
          setColumnType(other.getColumnType());
        }
        if (other.hasColumnName()) {
          setColumnName(other.getColumnName());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasTtl()) {
          setTtl(other.getTtl());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRowKey()) {
          
          return false;
        }
        if (!hasDeletedAt()) {
          
          return false;
        }
        if (!hasColumnName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netflix.aegisthus.message.AegisthusProtos.Column parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netflix.aegisthus.message.AegisthusProtos.Column) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes rowKey = 1;
      private com.google.protobuf.ByteString rowKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes rowKey = 1;</code>
       */
      public boolean hasRowKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes rowKey = 1;</code>
       */
      public com.google.protobuf.ByteString getRowKey() {
        return rowKey_;
      }
      /**
       * <code>required bytes rowKey = 1;</code>
       */
      public Builder setRowKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rowKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes rowKey = 1;</code>
       */
      public Builder clearRowKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rowKey_ = getDefaultInstance().getRowKey();
        onChanged();
        return this;
      }

      // required int64 deletedAt = 2;
      private long deletedAt_ ;
      /**
       * <code>required int64 deletedAt = 2;</code>
       */
      public boolean hasDeletedAt() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 deletedAt = 2;</code>
       */
      public long getDeletedAt() {
        return deletedAt_;
      }
      /**
       * <code>required int64 deletedAt = 2;</code>
       */
      public Builder setDeletedAt(long value) {
        bitField0_ |= 0x00000002;
        deletedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 deletedAt = 2;</code>
       */
      public Builder clearDeletedAt() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deletedAt_ = 0L;
        onChanged();
        return this;
      }

      // optional .aegisthus.Column.ColumnType columnType = 3 [default = NORMAL];
      private com.netflix.aegisthus.message.AegisthusProtos.Column.ColumnType columnType_ = com.netflix.aegisthus.message.AegisthusProtos.Column.ColumnType.NORMAL;
      /**
       * <code>optional .aegisthus.Column.ColumnType columnType = 3 [default = NORMAL];</code>
       */
      public boolean hasColumnType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .aegisthus.Column.ColumnType columnType = 3 [default = NORMAL];</code>
       */
      public com.netflix.aegisthus.message.AegisthusProtos.Column.ColumnType getColumnType() {
        return columnType_;
      }
      /**
       * <code>optional .aegisthus.Column.ColumnType columnType = 3 [default = NORMAL];</code>
       */
      public Builder setColumnType(com.netflix.aegisthus.message.AegisthusProtos.Column.ColumnType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        columnType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .aegisthus.Column.ColumnType columnType = 3 [default = NORMAL];</code>
       */
      public Builder clearColumnType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        columnType_ = com.netflix.aegisthus.message.AegisthusProtos.Column.ColumnType.NORMAL;
        onChanged();
        return this;
      }

      // required bytes columnName = 4;
      private com.google.protobuf.ByteString columnName_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes columnName = 4;</code>
       */
      public boolean hasColumnName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes columnName = 4;</code>
       */
      public com.google.protobuf.ByteString getColumnName() {
        return columnName_;
      }
      /**
       * <code>required bytes columnName = 4;</code>
       */
      public Builder setColumnName(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        columnName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes columnName = 4;</code>
       */
      public Builder clearColumnName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        columnName_ = getDefaultInstance().getColumnName();
        onChanged();
        return this;
      }

      // optional bytes value = 5;
      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes value = 5;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes value = 5;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>optional bytes value = 5;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes value = 5;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      // optional int64 timestamp = 6;
      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 6;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 timestamp = 6;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 6;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000020;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 6;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 ttl = 7;
      private long ttl_ ;
      /**
       * <code>optional int64 ttl = 7;</code>
       */
      public boolean hasTtl() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int64 ttl = 7;</code>
       */
      public long getTtl() {
        return ttl_;
      }
      /**
       * <code>optional int64 ttl = 7;</code>
       */
      public Builder setTtl(long value) {
        bitField0_ |= 0x00000040;
        ttl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 ttl = 7;</code>
       */
      public Builder clearTtl() {
        bitField0_ = (bitField0_ & ~0x00000040);
        ttl_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:aegisthus.Column)
    }

    static {
      defaultInstance = new Column(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:aegisthus.Column)
  }

  public interface RowOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes rowKey = 1;
    /**
     * <code>required bytes rowKey = 1;</code>
     */
    boolean hasRowKey();
    /**
     * <code>required bytes rowKey = 1;</code>
     */
    com.google.protobuf.ByteString getRowKey();

    // required int64 deletedAt = 2;
    /**
     * <code>required int64 deletedAt = 2;</code>
     */
    boolean hasDeletedAt();
    /**
     * <code>required int64 deletedAt = 2;</code>
     */
    long getDeletedAt();

    // repeated .aegisthus.Column column = 3;
    /**
     * <code>repeated .aegisthus.Column column = 3;</code>
     */
    java.util.List<com.netflix.aegisthus.message.AegisthusProtos.Column> 
        getColumnList();
    /**
     * <code>repeated .aegisthus.Column column = 3;</code>
     */
    com.netflix.aegisthus.message.AegisthusProtos.Column getColumn(int index);
    /**
     * <code>repeated .aegisthus.Column column = 3;</code>
     */
    int getColumnCount();
    /**
     * <code>repeated .aegisthus.Column column = 3;</code>
     */
    java.util.List<? extends com.netflix.aegisthus.message.AegisthusProtos.ColumnOrBuilder> 
        getColumnOrBuilderList();
    /**
     * <code>repeated .aegisthus.Column column = 3;</code>
     */
    com.netflix.aegisthus.message.AegisthusProtos.ColumnOrBuilder getColumnOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code aegisthus.Row}
   */
  public static final class Row extends
      com.google.protobuf.GeneratedMessage
      implements RowOrBuilder {
    // Use Row.newBuilder() to construct.
    private Row(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Row(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Row defaultInstance;
    public static Row getDefaultInstance() {
      return defaultInstance;
    }

    public Row getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Row(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              rowKey_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              deletedAt_ = input.readInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                column_ = new java.util.ArrayList<com.netflix.aegisthus.message.AegisthusProtos.Column>();
                mutable_bitField0_ |= 0x00000004;
              }
              column_.add(input.readMessage(com.netflix.aegisthus.message.AegisthusProtos.Column.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          column_ = java.util.Collections.unmodifiableList(column_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netflix.aegisthus.message.AegisthusProtos.internal_static_aegisthus_Row_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netflix.aegisthus.message.AegisthusProtos.internal_static_aegisthus_Row_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netflix.aegisthus.message.AegisthusProtos.Row.class, com.netflix.aegisthus.message.AegisthusProtos.Row.Builder.class);
    }

    public static com.google.protobuf.Parser<Row> PARSER =
        new com.google.protobuf.AbstractParser<Row>() {
      public Row parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Row(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Row> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes rowKey = 1;
    public static final int ROWKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString rowKey_;
    /**
     * <code>required bytes rowKey = 1;</code>
     */
    public boolean hasRowKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes rowKey = 1;</code>
     */
    public com.google.protobuf.ByteString getRowKey() {
      return rowKey_;
    }

    // required int64 deletedAt = 2;
    public static final int DELETEDAT_FIELD_NUMBER = 2;
    private long deletedAt_;
    /**
     * <code>required int64 deletedAt = 2;</code>
     */
    public boolean hasDeletedAt() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 deletedAt = 2;</code>
     */
    public long getDeletedAt() {
      return deletedAt_;
    }

    // repeated .aegisthus.Column column = 3;
    public static final int COLUMN_FIELD_NUMBER = 3;
    private java.util.List<com.netflix.aegisthus.message.AegisthusProtos.Column> column_;
    /**
     * <code>repeated .aegisthus.Column column = 3;</code>
     */
    public java.util.List<com.netflix.aegisthus.message.AegisthusProtos.Column> getColumnList() {
      return column_;
    }
    /**
     * <code>repeated .aegisthus.Column column = 3;</code>
     */
    public java.util.List<? extends com.netflix.aegisthus.message.AegisthusProtos.ColumnOrBuilder> 
        getColumnOrBuilderList() {
      return column_;
    }
    /**
     * <code>repeated .aegisthus.Column column = 3;</code>
     */
    public int getColumnCount() {
      return column_.size();
    }
    /**
     * <code>repeated .aegisthus.Column column = 3;</code>
     */
    public com.netflix.aegisthus.message.AegisthusProtos.Column getColumn(int index) {
      return column_.get(index);
    }
    /**
     * <code>repeated .aegisthus.Column column = 3;</code>
     */
    public com.netflix.aegisthus.message.AegisthusProtos.ColumnOrBuilder getColumnOrBuilder(
        int index) {
      return column_.get(index);
    }

    private void initFields() {
      rowKey_ = com.google.protobuf.ByteString.EMPTY;
      deletedAt_ = 0L;
      column_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRowKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeletedAt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getColumnCount(); i++) {
        if (!getColumn(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, rowKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, deletedAt_);
      }
      for (int i = 0; i < column_.size(); i++) {
        output.writeMessage(3, column_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, rowKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, deletedAt_);
      }
      for (int i = 0; i < column_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, column_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.netflix.aegisthus.message.AegisthusProtos.Row parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.aegisthus.message.AegisthusProtos.Row parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.aegisthus.message.AegisthusProtos.Row parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.aegisthus.message.AegisthusProtos.Row parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.aegisthus.message.AegisthusProtos.Row parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.netflix.aegisthus.message.AegisthusProtos.Row parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.netflix.aegisthus.message.AegisthusProtos.Row parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.netflix.aegisthus.message.AegisthusProtos.Row parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.netflix.aegisthus.message.AegisthusProtos.Row parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.netflix.aegisthus.message.AegisthusProtos.Row parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.netflix.aegisthus.message.AegisthusProtos.Row prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code aegisthus.Row}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.netflix.aegisthus.message.AegisthusProtos.RowOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netflix.aegisthus.message.AegisthusProtos.internal_static_aegisthus_Row_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netflix.aegisthus.message.AegisthusProtos.internal_static_aegisthus_Row_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netflix.aegisthus.message.AegisthusProtos.Row.class, com.netflix.aegisthus.message.AegisthusProtos.Row.Builder.class);
      }

      // Construct using com.netflix.aegisthus.message.AegisthusProtos.Row.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getColumnFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rowKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        deletedAt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (columnBuilder_ == null) {
          column_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          columnBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netflix.aegisthus.message.AegisthusProtos.internal_static_aegisthus_Row_descriptor;
      }

      public com.netflix.aegisthus.message.AegisthusProtos.Row getDefaultInstanceForType() {
        return com.netflix.aegisthus.message.AegisthusProtos.Row.getDefaultInstance();
      }

      public com.netflix.aegisthus.message.AegisthusProtos.Row build() {
        com.netflix.aegisthus.message.AegisthusProtos.Row result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netflix.aegisthus.message.AegisthusProtos.Row buildPartial() {
        com.netflix.aegisthus.message.AegisthusProtos.Row result = new com.netflix.aegisthus.message.AegisthusProtos.Row(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rowKey_ = rowKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deletedAt_ = deletedAt_;
        if (columnBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            column_ = java.util.Collections.unmodifiableList(column_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.column_ = column_;
        } else {
          result.column_ = columnBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netflix.aegisthus.message.AegisthusProtos.Row) {
          return mergeFrom((com.netflix.aegisthus.message.AegisthusProtos.Row)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netflix.aegisthus.message.AegisthusProtos.Row other) {
        if (other == com.netflix.aegisthus.message.AegisthusProtos.Row.getDefaultInstance()) return this;
        if (other.hasRowKey()) {
          setRowKey(other.getRowKey());
        }
        if (other.hasDeletedAt()) {
          setDeletedAt(other.getDeletedAt());
        }
        if (columnBuilder_ == null) {
          if (!other.column_.isEmpty()) {
            if (column_.isEmpty()) {
              column_ = other.column_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureColumnIsMutable();
              column_.addAll(other.column_);
            }
            onChanged();
          }
        } else {
          if (!other.column_.isEmpty()) {
            if (columnBuilder_.isEmpty()) {
              columnBuilder_.dispose();
              columnBuilder_ = null;
              column_ = other.column_;
              bitField0_ = (bitField0_ & ~0x00000004);
              columnBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getColumnFieldBuilder() : null;
            } else {
              columnBuilder_.addAllMessages(other.column_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRowKey()) {
          
          return false;
        }
        if (!hasDeletedAt()) {
          
          return false;
        }
        for (int i = 0; i < getColumnCount(); i++) {
          if (!getColumn(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netflix.aegisthus.message.AegisthusProtos.Row parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netflix.aegisthus.message.AegisthusProtos.Row) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes rowKey = 1;
      private com.google.protobuf.ByteString rowKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes rowKey = 1;</code>
       */
      public boolean hasRowKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes rowKey = 1;</code>
       */
      public com.google.protobuf.ByteString getRowKey() {
        return rowKey_;
      }
      /**
       * <code>required bytes rowKey = 1;</code>
       */
      public Builder setRowKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rowKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes rowKey = 1;</code>
       */
      public Builder clearRowKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rowKey_ = getDefaultInstance().getRowKey();
        onChanged();
        return this;
      }

      // required int64 deletedAt = 2;
      private long deletedAt_ ;
      /**
       * <code>required int64 deletedAt = 2;</code>
       */
      public boolean hasDeletedAt() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 deletedAt = 2;</code>
       */
      public long getDeletedAt() {
        return deletedAt_;
      }
      /**
       * <code>required int64 deletedAt = 2;</code>
       */
      public Builder setDeletedAt(long value) {
        bitField0_ |= 0x00000002;
        deletedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 deletedAt = 2;</code>
       */
      public Builder clearDeletedAt() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deletedAt_ = 0L;
        onChanged();
        return this;
      }

      // repeated .aegisthus.Column column = 3;
      private java.util.List<com.netflix.aegisthus.message.AegisthusProtos.Column> column_ =
        java.util.Collections.emptyList();
      private void ensureColumnIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          column_ = new java.util.ArrayList<com.netflix.aegisthus.message.AegisthusProtos.Column>(column_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.netflix.aegisthus.message.AegisthusProtos.Column, com.netflix.aegisthus.message.AegisthusProtos.Column.Builder, com.netflix.aegisthus.message.AegisthusProtos.ColumnOrBuilder> columnBuilder_;

      /**
       * <code>repeated .aegisthus.Column column = 3;</code>
       */
      public java.util.List<com.netflix.aegisthus.message.AegisthusProtos.Column> getColumnList() {
        if (columnBuilder_ == null) {
          return java.util.Collections.unmodifiableList(column_);
        } else {
          return columnBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .aegisthus.Column column = 3;</code>
       */
      public int getColumnCount() {
        if (columnBuilder_ == null) {
          return column_.size();
        } else {
          return columnBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .aegisthus.Column column = 3;</code>
       */
      public com.netflix.aegisthus.message.AegisthusProtos.Column getColumn(int index) {
        if (columnBuilder_ == null) {
          return column_.get(index);
        } else {
          return columnBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .aegisthus.Column column = 3;</code>
       */
      public Builder setColumn(
          int index, com.netflix.aegisthus.message.AegisthusProtos.Column value) {
        if (columnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureColumnIsMutable();
          column_.set(index, value);
          onChanged();
        } else {
          columnBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .aegisthus.Column column = 3;</code>
       */
      public Builder setColumn(
          int index, com.netflix.aegisthus.message.AegisthusProtos.Column.Builder builderForValue) {
        if (columnBuilder_ == null) {
          ensureColumnIsMutable();
          column_.set(index, builderForValue.build());
          onChanged();
        } else {
          columnBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aegisthus.Column column = 3;</code>
       */
      public Builder addColumn(com.netflix.aegisthus.message.AegisthusProtos.Column value) {
        if (columnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureColumnIsMutable();
          column_.add(value);
          onChanged();
        } else {
          columnBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .aegisthus.Column column = 3;</code>
       */
      public Builder addColumn(
          int index, com.netflix.aegisthus.message.AegisthusProtos.Column value) {
        if (columnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureColumnIsMutable();
          column_.add(index, value);
          onChanged();
        } else {
          columnBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .aegisthus.Column column = 3;</code>
       */
      public Builder addColumn(
          com.netflix.aegisthus.message.AegisthusProtos.Column.Builder builderForValue) {
        if (columnBuilder_ == null) {
          ensureColumnIsMutable();
          column_.add(builderForValue.build());
          onChanged();
        } else {
          columnBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aegisthus.Column column = 3;</code>
       */
      public Builder addColumn(
          int index, com.netflix.aegisthus.message.AegisthusProtos.Column.Builder builderForValue) {
        if (columnBuilder_ == null) {
          ensureColumnIsMutable();
          column_.add(index, builderForValue.build());
          onChanged();
        } else {
          columnBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aegisthus.Column column = 3;</code>
       */
      public Builder addAllColumn(
          java.lang.Iterable<? extends com.netflix.aegisthus.message.AegisthusProtos.Column> values) {
        if (columnBuilder_ == null) {
          ensureColumnIsMutable();
          super.addAll(values, column_);
          onChanged();
        } else {
          columnBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .aegisthus.Column column = 3;</code>
       */
      public Builder clearColumn() {
        if (columnBuilder_ == null) {
          column_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          columnBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .aegisthus.Column column = 3;</code>
       */
      public Builder removeColumn(int index) {
        if (columnBuilder_ == null) {
          ensureColumnIsMutable();
          column_.remove(index);
          onChanged();
        } else {
          columnBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .aegisthus.Column column = 3;</code>
       */
      public com.netflix.aegisthus.message.AegisthusProtos.Column.Builder getColumnBuilder(
          int index) {
        return getColumnFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .aegisthus.Column column = 3;</code>
       */
      public com.netflix.aegisthus.message.AegisthusProtos.ColumnOrBuilder getColumnOrBuilder(
          int index) {
        if (columnBuilder_ == null) {
          return column_.get(index);  } else {
          return columnBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .aegisthus.Column column = 3;</code>
       */
      public java.util.List<? extends com.netflix.aegisthus.message.AegisthusProtos.ColumnOrBuilder> 
           getColumnOrBuilderList() {
        if (columnBuilder_ != null) {
          return columnBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(column_);
        }
      }
      /**
       * <code>repeated .aegisthus.Column column = 3;</code>
       */
      public com.netflix.aegisthus.message.AegisthusProtos.Column.Builder addColumnBuilder() {
        return getColumnFieldBuilder().addBuilder(
            com.netflix.aegisthus.message.AegisthusProtos.Column.getDefaultInstance());
      }
      /**
       * <code>repeated .aegisthus.Column column = 3;</code>
       */
      public com.netflix.aegisthus.message.AegisthusProtos.Column.Builder addColumnBuilder(
          int index) {
        return getColumnFieldBuilder().addBuilder(
            index, com.netflix.aegisthus.message.AegisthusProtos.Column.getDefaultInstance());
      }
      /**
       * <code>repeated .aegisthus.Column column = 3;</code>
       */
      public java.util.List<com.netflix.aegisthus.message.AegisthusProtos.Column.Builder> 
           getColumnBuilderList() {
        return getColumnFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.netflix.aegisthus.message.AegisthusProtos.Column, com.netflix.aegisthus.message.AegisthusProtos.Column.Builder, com.netflix.aegisthus.message.AegisthusProtos.ColumnOrBuilder> 
          getColumnFieldBuilder() {
        if (columnBuilder_ == null) {
          columnBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.netflix.aegisthus.message.AegisthusProtos.Column, com.netflix.aegisthus.message.AegisthusProtos.Column.Builder, com.netflix.aegisthus.message.AegisthusProtos.ColumnOrBuilder>(
                  column_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          column_ = null;
        }
        return columnBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:aegisthus.Row)
    }

    static {
      defaultInstance = new Row(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:aegisthus.Row)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_aegisthus_Column_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_aegisthus_Column_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_aegisthus_Row_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_aegisthus_Row_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017aegisthus.proto\022\taegisthus\"\352\001\n\006Column\022" +
      "\016\n\006rowKey\030\001 \002(\014\022\021\n\tdeletedAt\030\002 \002(\003\0228\n\nco" +
      "lumnType\030\003 \001(\0162\034.aegisthus.Column.Column" +
      "Type:\006NORMAL\022\022\n\ncolumnName\030\004 \002(\014\022\r\n\005valu" +
      "e\030\005 \001(\014\022\021\n\ttimestamp\030\006 \001(\003\022\013\n\003ttl\030\007 \001(\003\"" +
      "@\n\nColumnType\022\n\n\006NORMAL\020\000\022\013\n\007DELETED\020\001\022\014" +
      "\n\010EXPIRING\020\002\022\013\n\007COUNTER\020\003\"K\n\003Row\022\016\n\006rowK" +
      "ey\030\001 \002(\014\022\021\n\tdeletedAt\030\002 \002(\003\022!\n\006column\030\003 " +
      "\003(\0132\021.aegisthus.ColumnB0\n\035com.netflix.ae" +
      "gisthus.messageB\017AegisthusProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_aegisthus_Column_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_aegisthus_Column_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_aegisthus_Column_descriptor,
              new java.lang.String[] { "RowKey", "DeletedAt", "ColumnType", "ColumnName", "Value", "Timestamp", "Ttl", });
          internal_static_aegisthus_Row_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_aegisthus_Row_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_aegisthus_Row_descriptor,
              new java.lang.String[] { "RowKey", "DeletedAt", "Column", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
